// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCekJmmWKGKEQ3QRi1eNmpo0va0ldqwQ8',
    appId: '1:689402195640:web:981aa04f652823abb5ce4d',
    messagingSenderId: '689402195640',
    projectId: 'fruit-hup-a00aa',
    authDomain: 'fruit-hup-a00aa.firebaseapp.com',
    storageBucket: 'fruit-hup-a00aa.firebasestorage.app',
    measurementId: 'G-ZR6L2HJ8RK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvL6innqsLcl8QFIKKMX-Pi_kBFSn11DE',
    appId: '1:689402195640:android:be4082839ca95b33b5ce4d',
    messagingSenderId: '689402195640',
    projectId: 'fruit-hup-a00aa',
    storageBucket: 'fruit-hup-a00aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBz2Njby0zQ7otD80fUb9pOXDup3E8piBc',
    appId: '1:689402195640:ios:703396f28e76da82b5ce4d',
    messagingSenderId: '689402195640',
    projectId: 'fruit-hup-a00aa',
    storageBucket: 'fruit-hup-a00aa.firebasestorage.app',
    iosBundleId: 'com.example.fruitApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBz2Njby0zQ7otD80fUb9pOXDup3E8piBc',
    appId: '1:689402195640:ios:703396f28e76da82b5ce4d',
    messagingSenderId: '689402195640',
    projectId: 'fruit-hup-a00aa',
    storageBucket: 'fruit-hup-a00aa.firebasestorage.app',
    iosBundleId: 'com.example.fruitApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCekJmmWKGKEQ3QRi1eNmpo0va0ldqwQ8',
    appId: '1:689402195640:web:9d3d4126eefd203ab5ce4d',
    messagingSenderId: '689402195640',
    projectId: 'fruit-hup-a00aa',
    authDomain: 'fruit-hup-a00aa.firebaseapp.com',
    storageBucket: 'fruit-hup-a00aa.firebasestorage.app',
    measurementId: 'G-6H0MRTG40F',
  );
}
